# Generated by Django 4.2.24 on 2025-09-20 00:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                (
                    "contato_nome",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nome do Contato",
                    ),
                ),
                ("telefone", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("unidade_medida", models.CharField(default="unidade", max_length=20)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INSUMO", "Insumo"),
                            ("PRODUTO_FINAL", "Produto Final"),
                        ],
                        default="INSUMO",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Unidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("endereco", models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="VendaDiaria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(default=django.utils.timezone.now)),
                ("quantidade", models.PositiveIntegerField(default=0)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.produto",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.unidade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoReposicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("CONCLUIDO", "Concluído"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "unidade_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.unidade",
                        verbose_name="Unidade de Destino",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_nota_fiscal",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número da NF-e",
                    ),
                ),
                (
                    "data_pedido",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data do Pedido"
                    ),
                ),
                (
                    "data_recebimento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data de Recebimento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("RECEBIDO", "Recebido"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.fornecedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Movimentacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SAIDA", "Saída"),
                            ("TRANSFERENCIA", "Transferência"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantidade", models.FloatField()),
                ("data", models.DateTimeField(auto_now_add=True)),
                (
                    "destino",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacao_destino",
                        to="estoque.unidade",
                    ),
                ),
                (
                    "origem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentacao_origem",
                        to="estoque.unidade",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemReposicao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade_solicitada", models.FloatField()),
                (
                    "pedido_reposicao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="estoque.pedidoreposicao",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "INSUMO"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedidoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.FloatField()),
                (
                    "preco_custo_unitario",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço de Custo Unitário",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="estoque.pedidocompra",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.FloatField()),
                (
                    "insumo",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "INSUMO"},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usado_em",
                        to="estoque.produto",
                    ),
                ),
                (
                    "produto_final",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "PRODUTO_FINAL"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientes",
                        to="estoque.produto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.FloatField(default=0)),
                ("estoque_minimo", models.FloatField(default=0)),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.produto",
                    ),
                ),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.unidade",
                    ),
                ),
            ],
            options={
                "unique_together": {("unidade", "produto")},
            },
        ),
    ]
