# Generated by Django 4.2.24 on 2025-09-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemreposicao",
            name="justificativa",
            field=models.CharField(
                blank=True,
                help_text="Ex: Perdas, evento especial, etc.",
                max_length=200,
                null=True,
            ),
        ),
    ]
