# Generated by Django 4.2.24 on 2025-09-21 00:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0002_itemreposicao_justificativa"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContagemEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_contagem",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "responsavel",
                    models.CharField(
                        help_text="Nome da pessoa que realizou a contagem",
                        max_length=100,
                    ),
                ),
                (
                    "finalizada",
                    models.BooleanField(
                        default=False,
                        help_text="Marca se os ajustes desta contagem já foram processados",
                    ),
                ),
                ("observacoes", models.TextField(blank=True, null=True)),
                (
                    "unidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.unidade",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="movimentacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("SAIDA", "Saída"),
                    ("TRANSFERENCIA", "Transferência"),
                    ("AJUSTE", "Ajuste de Estoque"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ItemContagemEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_sistema",
                    models.FloatField(
                        help_text="Quantidade que o sistema calculava ter no momento da contagem"
                    ),
                ),
                (
                    "quantidade_fisica",
                    models.FloatField(
                        help_text="Quantidade que foi contada fisicamente"
                    ),
                ),
                (
                    "contagem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="estoque.contagemestoque",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        limit_choices_to={"tipo": "INSUMO"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.produto",
                    ),
                ),
            ],
        ),
    ]
