# Generated by Django 4.2.24 on 2025-10-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0003_contagemestoque_alter_movimentacao_tipo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemcontagemestoque",
            name="quantidade_fisica",
            field=models.IntegerField(
                default=0, help_text="Quantidade que foi contada fisicamente"
            ),
        ),
        migrations.AlterField(
            model_name="itemcontagemestoque",
            name="quantidade_sistema",
            field=models.IntegerField(
                default=0,
                help_text="Quantidade que o sistema calculava ter no momento da contagem",
            ),
        ),
    ]
