# Generated by Django 4.2.24 on 2025-10-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0004_alter_itemcontagemestoque_quantidade_fisica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemreposicao",
            name="quantidade_enviada",
            field=models.FloatField(
                blank=True,
                help_text="Quantidade efetivamente enviada pela Cozinha. Preenchido ao concluir o pedido.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="pedidoreposicao",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("CONCLUIDO", "Concluído"),
                    ("CONCLUIDO_PARCIALMENTE", "Concluído Parcialmente"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDENTE",
                max_length=30,
            ),
        ),
    ]
