# Generated by Django 4.2.24 on 2025-10-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0005_itemreposicao_quantidade_enviada_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedidoreposicao",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDENTE", "Pendente"),
                    ("ENVIADO", "Enviado"),
                    ("CONCLUIDO", "Concluído"),
                    ("CONCLUIDO_PARCIALMENTE", "Concluído Parcialmente"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="PENDENTE",
                max_length=30,
            ),
        ),
    ]
