# Generated by Django 4.2.24 on 2026-03-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0006_alter_pedidoreposicao_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contagemestoque",
            name="finalizada",
        ),
        migrations.AddField(
            model_name="contagemestoque",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente (Aguardando ADM)"),
                    ("aprovado", "Aprovado (Estoque Atualizado)"),
                    ("cancelado", "Cancelado"),
                ],
                default="pendente",
                max_length=15,
            ),
        ),
    ]
